// Package requestgen turns a normalized OpenAPI spec into concrete HTTP requests,
// generating example values from schemas (ported/extended from BishopFox/sj).
package requestgen

import (
	"encoding/json"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/codejavu-inc/swaggervu/internal/spec"
	"github.com/getkin/kin-openapi/openapi3"
)

// Options controls value generation.
type Options struct {
	TestString  string
	CustomURL   string
	CustomEmail string
	CustomDate  string
	BaseURL     string // overrides server URL when set
	IncludeRisk bool   // include non-GET methods
}

// DefaultOptions returns sane defaults.
func DefaultOptions() Options {
	return Options{
		TestString:  "swaggervu",
		CustomURL:   "https://example.com",
		CustomEmail: "test@example.com",
		CustomDate:  "1990-01-01",
	}
}

// Request is a concrete generated HTTP request.
type Request struct {
	Method      string            `json:"method"`
	URL         string            `json:"url"`
	Path        string            `json:"path"` // template path (for grouping)
	Body        string            `json:"body,omitempty"`
	ContentType string            `json:"content_type,omitempty"`
	Headers     map[string]string `json:"headers,omitempty"`
}

// safeMethods are non-mutating and generated by default. Everything else
// (POST/PUT/PATCH/DELETE) is only generated when IncludeRisk is set, so the
// default scan never writes to the target.
var safeMethods = map[string]bool{"GET": true, "HEAD": true, "OPTIONS": true}

// ResolveBase returns the effective base URL Build will use: the explicit
// opts.BaseURL when set, otherwise the spec's server URL, trimmed of any
// trailing slash. Callers use it to avoid redundant re-scans against a base
// that matches the one already used.
func ResolveBase(s *spec.Spec, opts Options) string {
	base := opts.BaseURL
	if base == "" {
		base = serverURL(s)
	}
	return strings.TrimRight(base, "/")
}

// Build generates one request per operation in the spec.
func Build(s *spec.Spec, opts Options) []Request {
	if s == nil || s.Doc == nil || s.Doc.Paths == nil {
		return nil
	}
	base := ResolveBase(s, opts)

	var reqs []Request
	paths := make([]string, 0, s.Doc.Paths.Len())
	for p := range s.Doc.Paths.Map() {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		item := s.Doc.Paths.Value(p)
		if item == nil {
			continue
		}
		methods := make([]string, 0)
		for m := range item.Operations() {
			methods = append(methods, m)
		}
		sort.Strings(methods)
		for _, method := range methods {
			if !opts.IncludeRisk && !safeMethods[method] {
				continue
			}
			op := item.Operations()[method]
			reqs = append(reqs, buildOne(base, method, p, item, op, opts))
		}
	}
	return reqs
}

func buildOne(base, method, path string, item *openapi3.PathItem, op *openapi3.Operation, opts Options) Request {
	req := Request{Method: method, Path: path, Headers: map[string]string{}}
	resolvedPath := path
	query := url.Values{}

	params := append([]*openapi3.ParameterRef{}, item.Parameters...)
	params = append(params, op.Parameters...)
	for _, pref := range params {
		if pref == nil || pref.Value == nil {
			continue
		}
		pm := pref.Value
		val := paramValue(pm, opts)
		switch pm.In {
		case "path":
			resolvedPath = substitutePathParam(resolvedPath, pm.Name, val)
		case "query":
			query.Set(pm.Name, val)
		case "header":
			req.Headers[pm.Name] = val
		}
	}

	// Request body (OpenAPI 3 style; v2 bodies were converted by the loader).
	if op.RequestBody != nil && op.RequestBody.Value != nil {
		for ct, mt := range op.RequestBody.Value.Content {
			if mt == nil || mt.Schema == nil {
				continue
			}
			ex := GenerateExample(mt.Schema.Value, opts, map[*openapi3.Schema]bool{})
			switch {
			case strings.Contains(ct, "json"):
				if b, err := json.Marshal(ex); err == nil {
					req.Body = string(b)
					req.ContentType = "application/json"
				}
			case strings.Contains(ct, "x-www-form-urlencoded"):
				req.Body = formEncode(ex)
				req.ContentType = "application/x-www-form-urlencoded"
			default:
				if b, err := json.Marshal(ex); err == nil {
					req.Body = string(b)
					req.ContentType = ct
				}
			}
			break // one representative content type is enough
		}
	}

	u := base + resolvedPath
	if enc := query.Encode(); enc != "" {
		u += "?" + enc
	}
	req.URL = u
	return req
}

// substitutePathParam handles {id}, :id, and <id> placeholder styles.
func substitutePathParam(path, name, val string) string {
	val = url.PathEscape(val)
	path = strings.ReplaceAll(path, "{"+name+"}", val)
	path = strings.ReplaceAll(path, ":"+name, val)
	path = strings.ReplaceAll(path, "<"+name+">", val)
	return path
}

// paramValue picks a value for a parameter using schema + name heuristics.
// Array parameters are rendered comma-separated (the most broadly compatible
// collection format) rather than as a JSON array.
func paramValue(pm *openapi3.Parameter, opts Options) string {
	if pm.Schema != nil && pm.Schema.Value != nil {
		ex := GenerateExample(pm.Schema.Value, opts, map[*openapi3.Schema]bool{})
		if arr, ok := ex.([]any); ok {
			parts := make([]string, 0, len(arr))
			for _, it := range arr {
				parts = append(parts, toStr(it))
			}
			return strings.Join(parts, ",")
		}
		return toStr(ex)
	}
	return opts.TestString
}

// GenerateExample recursively produces an example value for a schema.
func GenerateExample(sch *openapi3.Schema, opts Options, visited map[*openapi3.Schema]bool) any {
	if sch == nil {
		return opts.TestString
	}
	if visited[sch] {
		return nil // break $ref cycles
	}
	visited[sch] = true
	defer delete(visited, sch)

	if sch.Example != nil {
		return sch.Example
	}
	if len(sch.Enum) > 0 {
		return sch.Enum[0]
	}
	if sch.Default != nil {
		return sch.Default
	}
	// allOf: merge object properties.
	if len(sch.AllOf) > 0 {
		merged := map[string]any{}
		for _, ref := range sch.AllOf {
			if ref != nil && ref.Value != nil {
				if m, ok := GenerateExample(ref.Value, opts, visited).(map[string]any); ok {
					for k, v := range m {
						merged[k] = v
					}
				}
			}
		}
		if len(merged) > 0 {
			return merged
		}
	}
	if len(sch.OneOf) > 0 && sch.OneOf[0].Value != nil {
		return GenerateExample(sch.OneOf[0].Value, opts, visited)
	}
	if len(sch.AnyOf) > 0 && sch.AnyOf[0].Value != nil {
		return GenerateExample(sch.AnyOf[0].Value, opts, visited)
	}

	switch {
	case sch.Type.Is("object") || len(sch.Properties) > 0:
		obj := map[string]any{}
		for name, pref := range sch.Properties {
			if pref == nil || pref.Value == nil {
				continue
			}
			obj[name] = contextValue(name, pref.Value, opts, visited)
		}
		return obj
	case sch.Type.Is("array"):
		if sch.Items != nil && sch.Items.Value != nil {
			return []any{GenerateExample(sch.Items.Value, opts, visited)}
		}
		return []any{}
	case sch.Type.Is("integer"):
		return 1
	case sch.Type.Is("number"):
		return 1
	case sch.Type.Is("boolean"):
		return true
	default:
		return opts.TestString
	}
}

// contextValue applies property-name heuristics (date/url/email) like sj.
func contextValue(name string, sch *openapi3.Schema, opts Options, visited map[*openapi3.Schema]bool) any {
	lower := strings.ToLower(name)
	if sch.Type != nil && sch.Type.Is("string") && len(sch.Enum) == 0 && sch.Example == nil {
		switch {
		case strings.Contains(lower, "date") || strings.Contains(lower, "time"):
			return opts.CustomDate
		case strings.Contains(lower, "email") || strings.Contains(lower, "mail"):
			return opts.CustomEmail
		case strings.Contains(lower, "url") || strings.Contains(lower, "uri") || strings.Contains(lower, "link"):
			return opts.CustomURL
		}
	}
	return GenerateExample(sch, opts, visited)
}

func serverURL(s *spec.Spec) string {
	if s.Doc != nil && len(s.Doc.Servers) > 0 {
		return s.Doc.Servers[0].URL
	}
	if s.SourceURL != "" {
		if u, err := url.Parse(s.SourceURL); err == nil {
			return u.Scheme + "://" + u.Host
		}
	}
	return ""
}

func toStr(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case nil:
		return ""
	default:
		if b, err := json.Marshal(x); err == nil {
			return string(b)
		}
		return ""
	}
}

func formEncode(ex any) string {
	m, ok := ex.(map[string]any)
	if !ok {
		return ""
	}
	vals := url.Values{}
	for k, v := range m {
		vals.Set(k, toStr(v))
	}
	return vals.Encode()
}
